# Random Network Monte-Carlo config for Piston Leak ODE + ABM simulation
meta:
  description: >
    500-run ensemble, random network topology (Erdos-Renyi)
  author: GASLIT-420
  date: 2025-04-21
  version: 0.1

ensemble:
  runs: 500
  random_seed: 42         # because Hitchhiker's

time:
  dt: 1.0                 # one timestep = one media cycle (~1 day)
  t_max: 365              # one pandemic year

parameters:
  # ODE coefficients (same as baseline)
  alpha1: 0.6
  beta1: 0.3
  gamma1: 0.2
  alpha2: 0.5
  beta2: 0.25
  k_policy: 0.8
  delta: 0.15

  # Noise model (same as baseline)
  noise_sigma: 0.1
  leak_frequency: 0.05

  # Agent-based layer with random network
  network:
    type: erdos_renyi
    n_agents: 3000
    k: 6                 # Converted to edge probability p = k/(n-1) internally
  influence_field:
    believer_weight: 1.0
    skeptic_weight: 1.2
    agnostic_weight: 0.8

  # Collapse threshold (same as baseline)
  epsilon_overlap: 0.15
  trust_slope_threshold: -0.05
  entropy_critical: 1.2

output:
  path: results/network_random/
  save_timeseries: true
  save_summary: true
  plots: true