# Trust Decay Sensitivity Monte-Carlo config for Piston Leak ODE + ABM simulation
meta:
  description: >
    Parameter sweep of trust decay rate (alpha1)
  author: GASLIT-420
  date: 2025-04-21
  version: 0.1

ensemble:
  runs: 100
  random_seed: 42
  parameter_sweep: true
  sweep_parameter: "alpha1"
  sweep_values: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

time:
  dt: 1.0                 # one timestep = one media cycle (~1 day)
  t_max: 365              # one pandemic year

parameters:
  # ODE coefficients (alpha1 will be overridden by sweep)
  alpha1: 0.6             # Trust decay vs entropy
  beta1: 0.3              # Transparency restoration boost
  gamma1: 0.2             # Suppression penalty on trust

  alpha2: 0.5             # Entropy gain from suppression
  beta2: 0.25             # Entropy damped by rising trust

  k_policy: 0.8           # Aggressiveness of narrative control
  delta: 0.15             # Suppression fatigue rate

  # Noise model
  noise_sigma: 0.1        # Std-dev of exogenous leak shocks
  leak_frequency: 0.05    # Probability of a leak per timestep

  # Agent-based layer
  network:
    type: watts_strogatz
    n_agents: 3000
    k: 6
    p_rewire: 0.2
  influence_field:
    believer_weight: 1.0
    skeptic_weight: 1.2
    agnostic_weight: 0.8

  # Collapse threshold (Îµ-band overlap)
  epsilon_overlap: 0.15
  trust_slope_threshold: -0.05
  entropy_critical: 1.2

output:
  path: results/sensitivity_trust_decay/
  save_timeseries: true
  save_summary: true
  plots: true
  parameter_heatmap: true